// flow-typed signature: d925e863b40c8a6729f7f2d287ada508
// flow-typed version: <<STUB>>/@types/moment_v^2.13.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/moment' {
  declare module.exports: any;
}
