// flow-typed signature: 35b8306048d38bd4e04b1d50151c6e03
// flow-typed version: <<STUB>>/@types/react-native_v^0.57.11/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-native' {
  declare module.exports: any;
}
