// flow-typed signature: 9ce82408981953aeaef2057ad685ceab
// flow-typed version: <<STUB>>/react-navigation-transitions_v^1.0.6/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-transitions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-transitions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-transitions/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-transitions/src/index.js' {
  declare module.exports: $Exports<'react-navigation-transitions/src/index'>;
}
