// flow-typed signature: 8a8f83707dae08138765b37616d56939
// flow-typed version: <<STUB>>/react-native-select-contact_vhttps://git.sfxdx.ru/lapo/react-native-select-contact.git#master/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-select-contact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-select-contact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-select-contact/index' {
  declare module.exports: $Exports<'react-native-select-contact'>;
}
declare module 'react-native-select-contact/index.js' {
  declare module.exports: $Exports<'react-native-select-contact'>;
}
