// flow-typed signature: a7b003981a15dfc6a9a80e7cac433923
// flow-typed version: <<STUB>>/react-native-pdf-lib_v^0.2.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-pdf-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-pdf-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-pdf-lib/jest/jest-setup' {
  declare module.exports: any;
}

declare module 'react-native-pdf-lib/js/__tests__/PDFDocument.test' {
  declare module.exports: any;
}

declare module 'react-native-pdf-lib/js/__tests__/PDFLib.test' {
  declare module.exports: any;
}

declare module 'react-native-pdf-lib/js/__tests__/PDFPage.test' {
  declare module.exports: any;
}

declare module 'react-native-pdf-lib/js/src/PDFDocument' {
  declare module.exports: any;
}

declare module 'react-native-pdf-lib/js/src/PDFLib' {
  declare module.exports: any;
}

declare module 'react-native-pdf-lib/js/src/PDFPage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-pdf-lib/index' {
  declare module.exports: $Exports<'react-native-pdf-lib'>;
}
declare module 'react-native-pdf-lib/index.js' {
  declare module.exports: $Exports<'react-native-pdf-lib'>;
}
declare module 'react-native-pdf-lib/jest/jest-setup.js' {
  declare module.exports: $Exports<'react-native-pdf-lib/jest/jest-setup'>;
}
declare module 'react-native-pdf-lib/js/__tests__/PDFDocument.test.js' {
  declare module.exports: $Exports<'react-native-pdf-lib/js/__tests__/PDFDocument.test'>;
}
declare module 'react-native-pdf-lib/js/__tests__/PDFLib.test.js' {
  declare module.exports: $Exports<'react-native-pdf-lib/js/__tests__/PDFLib.test'>;
}
declare module 'react-native-pdf-lib/js/__tests__/PDFPage.test.js' {
  declare module.exports: $Exports<'react-native-pdf-lib/js/__tests__/PDFPage.test'>;
}
declare module 'react-native-pdf-lib/js/src/PDFDocument.js' {
  declare module.exports: $Exports<'react-native-pdf-lib/js/src/PDFDocument'>;
}
declare module 'react-native-pdf-lib/js/src/PDFLib.js' {
  declare module.exports: $Exports<'react-native-pdf-lib/js/src/PDFLib'>;
}
declare module 'react-native-pdf-lib/js/src/PDFPage.js' {
  declare module.exports: $Exports<'react-native-pdf-lib/js/src/PDFPage'>;
}
