# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lapo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lapo
  # source 'https://github.com/CocoaPods/Specs.git'
  pod 'Zip', '~> 1.1'
  pod 'SQLite.swift', '~> 0.11.5'
  
  pod 'Fabric'
  pod 'Crashlytics'
#  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
#
#
#  pod 'React', :path => '../node_modules/react-native', :subspecs => [
#  'RCTLinkingIOS',
#  ]
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'


#  pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'

#  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
#pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
#


#  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

end
